---
title: "index"
author: "Mark Morales"
date: "November 30, 2017"
output: 
  html_document:
    code_folding: hide
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

## scatterplot

```{r scatterplot}
#mpg

g <- ggplot(data = mpg, aes(x = displ, y = hwy)) + 
  geom_point()

```

## I need color

```{r color}
g <- ggplot(data = mpg, aes(x = displ, y = hwy, color = class)) +
  geom_point()
g
```

## Change color to shape, for a b&w plot

``` {r shape}
g <- ggplot(data = mpg, aes(x = displ, y = hwy, shape = class)) +
  geom_point()
g
```

## now let's play with the size

``` {r size}
g <- ggplot(data = mpg, aes(x = cty, y = hwy, size = class, color = fl)) +
  geom_point(alpha = 0.4)
g
```

```{r fix color}
g <- ggplot(data = mpg, aes(x = cty, y = hwy, size = class)) +
  geom_point(alpha = 0.4, color = "blue")
g
```

## Exercise 5.5

1. What’s gone wrong with this code?

```{r fix the code}
 ggplot(data = mpg) + 
      geom_point(aes(x = displ, y = hwy, color = "blue"))
                 ### The color should be outside of the asesthetic
 ggplot(data = mpg) + 
      geom_point(aes(x = displ, y = hwy), color = "blue")
```

2. Plot hwy vs displ and have the point color to indicate cty mpg.

```{r number 2}
ggplot(data = mpg, aes(x = displ, y = hwy), color = cty) + 
  geom_point()
```

Note: finish these exercises later

```{r multiple_geoms}

ggplot(data = mpg) + 
  geom_point(aes(x = displ, y = hwy)) + 
  geom_smooth(aes(x = displ, y = hwy))

ggplot(data = mpg, aes(x = hwy, y = displ)) + 
  geom_point() + 
  geom_smooth() + 
  labs(title = "Replationship b/w engine size & MPG",
       x = "Highway MPG",
       y = "Engine Displacement (liters)") + 
  theme_classic() + 
  theme(text = element_text(size = 16))
```

## Data Wrangling with 'dplyr'

```{r}

gapminder <- readr::read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/gapminder.csv")

### some useful functions to get to know your data
head(gapminder) ### shows first six rows of the data
tail(gapminder) ### shows last six rows of the data

### check the structure of your data
str(gapminder)

### collumn names
names(gapminder)

### dimension of the data
dim(gapminder)
ncol(gapminder)
nrow(gapminder)

### combine with c()
c(nrow(gapminder), ncol(gapminder))

### summary statistics
summary(gapminder)

### for everything above, we were operating on the whole gapminder dataset

```

### Actually working with dplyr

filter
```{r filter}
filter(gapminder, lifeExp < 29)

filter(gapminder, country == "Mexico")

mean(filter(gapminder, country == "Sweden")$lifeExp)

```


piper operator
```{r operator}
gapminder %>% head(3)

gapminder %>%
  filter(country == "Sweden") %>%
  summarize(mean_lifeExp = mean(lifeExp))


```

select() by collumns
```{r select}
### select 2 columns
select(gapminder, year, lifeExp)

### with the pipe operator
gapminder %>%
  select(year, lifeExp) %>%
  tail()

### combine what we have learned 
gapminder %>%
  filter(country == "Cambodia") %>%
  select(country, year, pop, gdpPercap)

### same as above
gapminder %>%
  filter(country == "Cambodia") %>%
  select(-continent, -lifeExp)

### alternatively using base R.
gapminder[,c(1:3, 5)]

```

mutate() to add columns
```{r mutate}
gapminder %>%
  mutate(gdp = pop * gdpPercap)

### let's add an index
gapminder %>%
  mutate(index = 1:nrow(gapminder)) %>%
  tail()

### combine these new columns
gapminder %>%
  mutate(gdp = pop * gdpPercap ,index = 1:nrow(gapminder)) %>%
  tail()
  
gapminder %>%
  filter(country == c("Egypt", "Vietnam"))

### Find the maximum gdpPercap of Egypt and Vietnam Create a new column.
gapminder %>%
  filter(country == "Egypt" %in% "Vietnam") %>%
  mutate(max_gdpPercap = max(gdpPercap))

### group_by so that we can 2 maxes
gapminder %>%
  filter(country %in% c("Egypt", "Vietnam")) %>%
  group_by(country) %>%
  summarize(max_gdpPercap = max(gdpPercap))

gapminder %>%
  group_by(country) %>%
  summarize(max_gdpPercap = max(gdpPercap))
  
```
